apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: spring-boot
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/docker-spring-angular: "true"
        io.kompose.service: spring-boot
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Berlin
            - name: angular.service.base-path
              value: http://localhost
            - name: spring.datasource.password
              value: develop
            - name: spring.datasource.url
              value: jdbc:mysql://db:3306/dockerSpringAngular
            - name: spring.datasource.username
              value: brockel
          image: rainerdiekmann/dockerspringangularuser:backend
          name: spring-boot
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
